export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILS = 'FETCH_INGREDIENTS_FAILS'

// orders

export const GET_ORDERS = 'GET_ORDERS'
export const INIT_ORDERS = 'INIT_ORDERS'
export const FAIL_FETCH_ORDERS = 'FAIL_FETCH_ORDERS'

// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCESS = 'AUTH_SUCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
